apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: new-nginx
  name: new-nginx
spec:
  containers:
  - image: nginx
    name: new-nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
