apiVersion: v1
kind: Pod
metadata:
  labels:
  name: nignx-storage
spec:
  containers:
  - image: nginx
    name: nignx
    volumeMounts:
      - mountPath: /scratch
        name: scratch-volume
  volumes:
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi
