datadog:
  apiKeyExistingSecret: datadog-secret
  site: datadoghq.com

  logs:
    enabled: true
    containerCollectAll: true

  apm:
    portEnabled: true
    socketEnabled: false
    port: 8126 # default
    instrumentation:
      enabled: true
      libVersions:
         python: "2"
