apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
    tags.datadoghq.com/env: "test"
    tags.datadoghq.com/service: "mealie"
    tags.datadoghq.com/version: "1"
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
        admission.datadog.com/enabled: "true"
        tags.datadoghq.com/env: "test"
        tags.datadoghq.com/service: "mealie"
        tags.datadoghq.com/version: "1"
      annotations:
        admission.datadog.com/python-lib.version: "v2.21.1"
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:v1.3.2
        name: mealie
        ports:
          - containerPort: 9000
