apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
    tags.datadoghq.com/env: "test" # Unified service tag - Deployment Env tag
    tags.datadoghq.com/service: "my-service" # Unified service tag - Deployment Service tag
    tags.datadoghq.com/version: "1.1" # Unified service tag - Deployment Version tag
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: "test" # Unified service tag - Pod Env tag
        tags.datadoghq.com/service: "my-service" # Unified service tag - Pod Service tag
        tags.datadoghq.com/version: "1.1" # Unified service tag - Pod Version tag
        app: mealie
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:v1.3.2
        name: mealie
        ports:
          - containerPort: 9000
        env:
          - name: DD_LOGS_INJECTION
            value: 'true'
          - name: DD_TRACE_STARTUP_LOGS
            value: 'true'
          - name: DD_TRACE_DEBUG
            value: 'true'
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
